### ISSUE TITLE
Error When Writing out GT_donors.vcf

### ISSUE THREAD

**Issue by drneavin** [PMBio/vireo#4]
Hi there,

I am working with vireo v0.1.8 in python. I am running the command:
```
vireo -c $CELL_DATA -d $DONOR_GT_FILE -o $OUT -N 5
```
 and I have received the following error when it is trying to write out the final vcf:
```
Traceback (most recent call last):
  File "/path/to/bin/vireo", line 11, in <module>
    load_entry_point('vireoSNP==0.1.8', 'console_scripts', 'vireo')()
  File "/path/to/lib/python3.7/site-packages/vireoSNP-0.1.8-py3.7.egg/vireoSNP/vireo.py", line 232, in main
  File "/path/to/lib/python3.7/site-packages/vireoSNP-0.1.8-py3.7.egg/vireoSNP/utils/vcf_utils.py", line 223, in write_VCF
  File "path/to/lib/python3.7/site-packages/vireoSNP-0.1.8-py3.7.egg/vireoSNP/utils/vcf_utils.py", line 223, in <listcomp>
IndexError: list index out of range
```
It writes the header but nothing else for the vcf. For reference this is the header:
```##fileformat=VCFv4.2
##source=cellSNP_v0.1.3
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=.,Description="Filter info not available">
##INFO=<ID=DP,Number=1,Type=Integer,Description="total counts for ALT and REF">
##INFO=<ID=AD,Number=1,Type=Integer,Description="total counts for ALT">
##INFO=<ID=OTH,Number=1,Type=Integer,Description="total counts for other bases from REF and ALT">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GL,Number=3,Type=String,Description="Genotype likelihood">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="total counts for ALT and REF">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="total counts for ALT">
##FORMAT=<ID=OTH,Number=1,Type=Integer,Description="total counts for other bases from REF and ALT">
##FORMAT=<ID=ALL,Number=5,Type=Integer,Description="total counts for all bases in order of A,C,G,T,N">
##contig=<ID=1>
##contig=<ID=2>
##contig=<ID=3>
##contig=<ID=4>
##contig=<ID=5>
##contig=<ID=6>
##contig=<ID=7>
##contig=<ID=8>
##contig=<ID=9>
##contig=<ID=10>
##contig=<ID=11>
##contig=<ID=12>
##contig=<ID=13>
##contig=<ID=14>
##contig=<ID=15>
##contig=<ID=16>
##contig=<ID=17>
##contig=<ID=18>
##contig=<ID=19>
##contig=<ID=20>
##contig=<ID=21>
##contig=<ID=22>
##contig=<ID=X>
##contig=<ID=Y>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  193.CEL      146.CEL      133.CEL donor1  donor2  donor3  donor4
```
The number of individuals in this file should be 5 (only 3 genotyped) so I'm not sure why there are so many extra donors.

Any suggestions?

Thanks!

**Comment by huangyh09** [comment]
Hi,

This indeed looks odd, but I can't tell the issue immediately. Could you provide more details, e.g., the log print out? Also, I assume that when you don't specify the donor_vcf file, vireo works properly, right?

Thanks,
Yuanhua

**Comment by drneavin** [comment]
Yes, you are right, I just ran 
``` vireo -c $CELL_DATA -o $OUT -N 5```
and had no errors.

Here is the log print out for 
``` vireo -c $CELL_DATA -d $DONOR_GT_FILE -o $OUT -N 5 ```
```
[vireo] Loading cell VCF file ...
[vireo] Loading cell VCF file, done.
[vireo] Loading donor VCF file ...
[vireo] 285 out 1379 variants matched to donor VCF
[vireo] Loading donor VCF file, done.
[vireo] Demultiplex 1442 cells to 5 donors with 285 variants.
[vireo] warm-up: 50 random initializations for 7 clusters...
donor1  donor6  donor0  donor5  donor4  donor3  donor2
306     271     297     140     116     91      221
[vireo] warm-up: lower bound ranges [-13770.6, -12717.9, -11990.2]
[vireo] pre-RUN: finding 4 from 5 donors without GT ...
donor4  donor0  donor1  donor2  donor3
133     281     502     305     132
[vireo] main RUN with warm initials and tuned GT ...
[vireo] main RUN: 27 iterations; lower bound -11725.8
[vireo] beta parameters for binomial rate:
[[229.2 15526.1]
 [8082.9 9962.8]
 [8594.6 164.4]]
133.CEL      146.CEL      193.CEL      donor1  doublet unassigned
274     483     244     109     65      267
Traceback (most recent call last):
  File "/share/ClusterShare/software/contrib/sccg/anaconda3/bin/vireo", line 11, in <module>
    load_entry_point('vireoSNP==0.1.8', 'console_scripts', 'vireo')()
  File "/share/ClusterShare/software/contrib/sccg/anaconda3/lib/python3.7/site-packages/vireoSNP-0.1.8-py3.7.egg/vireoSNP/vireo.py", line 232, in main
  File "/share/ClusterShare/software/contrib/sccg/anaconda3/lib/python3.7/site-packages/vireoSNP-0.1.8-py3.7.egg/vireoSNP/utils/vcf_utils.py", line 223, in write_VCF
  File "/share/ClusterShare/software/contrib/sccg/anaconda3/lib/python3.7/site-packages/vireoSNP-0.1.8-py3.7.egg/vireoSNP/utils/vcf_utils.py", line 223, in <listcomp>
IndexError: list index out of range
```

Thanks for your hep!

**Comment by drneavin** [comment]
I also just realized that when I use genotype data, vireo reports for one less individual than the number of individuals that I tell it are in the multiplexed sample. In other words, it only indicates 4 individuals when there are 5 individuals in the multiplexed sample. I think this may contribute to the vcf writing issue. Here is the summary.tsv when N = 5:
```
ar1    Freq
133.CEL      274
146.CEL      483
193.CEL      244
donor1  109
doublet 65
unassigned      267
```
The command for that output was:
```vireo -c $CELL_DATA -d $DONOR_GT_FILE -o $OUT -N 5```

-Drew

**Comment by drneavin** [comment]
Yuanhua,

I'm not sure that I fully understand what you mean by a sample that "dropped out". If you mean that there aren't any cells from that individuals in the multiplexed batch, I don't think that is the case because I find all samples in the batch when I run without genotyping information. Further, this is consistently happening across 10 multiplexed batches (I have just provided the smallest one as an example).

I just ran what you suggested and here is the output:
``` Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vireoSNP import load_VCF
>>> from vireoSNP.utils.vcf_utils import parse_donor_GPb
>>> donor_vcf = load_VCF("SUB2019_10_09_MoST_SNP_genotypesRprocessedNA_rmSORTED.vcf.gz", biallelic_only=True, sparse=False, format_list=["PL"])
>>> donor_GPb = parse_donor_GPb(donor_vcf['GenoINFO']["PL"], "PL")
>>> print(donor_GPb.shape)
(285, 3, 1)
>>> print(donor_vcf['samples'])
['193.CEL', '146.CEL', '133.CEL']```

I'll send you the first few lines of my vcf by email as well.

Thanks,
Drew

**Comment by huangyh09** [comment]
Hi Drew,

Thanks for checking this and sending through the test file. It looks that the `PL` tag for gentoype (Phred-scaled likelihood) is not available and introduce false values. This bug has been probably introduced in recent upgrade for supporting arbitrary FORMAT tag in donor vcf file.

In short, you can add `-t GT` in your command line, and it should work. I will fix this bug to automatically detect the gentoype tag in new release.

Thanks a lot!
Yuanhua

**Comment by drneavin** [comment]
Great, pretty easy fix. Thanks for working to figure out the solution!

Cheers,
Drew

**Comment by huangyh09** [comment]
Hi Drew,

BTW, the number of SNPs (i.e., 1379) in your cell CVF seems only marginally sufficient. If you got too many unassigned cells, you could try some efforts to increase the usable SNPs, e.g., pileup ~7 million common human SNPs (AF5e2): https://sourceforge.net/projects/cellsnp/files/SNPlist/. Also, you could consider impute your known genotype if it is human data and you haven't done so.

Best
Yuanhua
